title: Напиши запит для генератора зображень ШІ
hero_image: images/banner.png
description: Дізнайся, як створити ефективні запити для генераторів зображень ШІ
version: 4
listed: true
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Що ти зробиш
  - 
    title: Напиши запит для генератора зображень ШІ
    completion:
      - engaged
      - internal
      - external
  - 
    title: Що ти тепер вмієш?
    completion:
