---
title: Geef een aanwijzing aan een AI afbeeldingsgenerator
hero_image: images/banner.png
description: Ontdek hoe je goede prompts voor AI afbeeldingsgeneratoren maakt
version: 4
listed: true
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Wat ga je maken
    completion:
      - engaged
  - title: Geef een aanwijzing aan een AI afbeeldingsgenerator
    completion:
      - internal
    completion:
      - external
