title: Geef een aanwijzing aan een AI afbeeldingsgenerator
hero_image: images/banner.png
description: Ontdek hoe je goede prompts voor AI afbeeldingsgeneratoren maakt
version: 4
listed: true
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Wat ga je maken
  - 
    title: Geef een aanwijzing aan een AI afbeeldingsgenerator
    completion:
      - engaged
      - internal
      - external
  - 
    title: Wat kun je nu doen?
    completion:
