title: Prompt an AI image generator
hero_image: images/banner.png
description: Explore how to create good prompts for AI image generators
version: 4
listed: true
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: What you will make
    completion:
    - engaged
  - title: Prompt an AI image generator
    completion:
    - internal
  - title: What can you do now?
    completion: 
    - external
