---
title: Prompt para criar imagem com IA
hero_image: images/banner.png
description: Explore como criar bons prompts para geradores de imagens de IA
version: 4
listed: true
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: O que você fará
    completion:
      - engaged
  - title: Prompt para criar imagem com IA
    completion:
      - internal
  - title: O que você pode fazer agora?
    completion:
      - external
