title: Crear un generador de imágenes de IA
hero_image: images/banner.png
description: Explorar cómo crear buenas sugerencias para los generadores de imágenes IA
version: 4
listed: true
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Lo que harás
    completion:
      - engaged
  - 
    title: Crear un generador de imágenes de IA
    completion:
      - internal
  - 
    title: '¿Qué puedes hacer ahora?'
    completion:
      - external
