title: Prompt an AI image generator
hero_image: images/banner.png
description: Explore how to create good prompts for AI image generators
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Ce que tu vas faire
  - 
    title: Prompt an AI image generator
    completion:
      - engaged
      - internal
  - 
    title: Que peux-tu faire maintenant ?
    completion:
      - external
