title: Prompt an AI image generator
hero_image: images/banner.png
description: Explore how to create good prompts for AI image generators
version: 4
listed: true
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Cosa creerai
  - 
    title: Prompt an AI image generator
    completion:
      - engaged
      - internal
      - external
  - 
    title: Cosa puoi fare adesso?
    completion:
