title: Bir yapay zekâ görsel oluşturucuya komut ver
hero_image: images/banner.png
description: Yapay zekâ görüntü oluşturucuları için iyi komutlar oluşturmanın yollarını keşfedin
version: 4
listed: true
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Ne yapacaksınız
    completion:
    - engaged
  - title: Bir yapay zekâ görsel oluşturucuya komut ver
    completion:
    - internal
    completion: 
    - external
    